# Use postgres/example user/password credentials
version: '3.9'

services:

  postgresql:
    image: postgres:17
    container_name: postgres-db
    restart: always
    # set shared memory limit when using docker-compose
#    shm_size: 128mb
    volumes:
      - ../docker/data:/var/lib/postgresql/data
    # or set shared memory limit when deploy via swarm stack
    # volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: local1234
    ports:
      - "5432:5432"

